include("${CMAKE_CURRENT_LIST_DIR}/sdk10-version.cmake")

if (PACKAGE_FIND_VERSION)
	string(REGEX MATCH "^10\\.[^.]+\\.[^.]+\\.([0-9]+)$" version_match "${PACKAGE_FIND_VERSION}")
	if (NOT version_match)
		return()
	endif()
	if (NOT "${CMAKE_MATCH_1}" EQUAL "${SDK10_VERSION}")
		return()
	endif()
endif()

if (NOT DEFINED DEVICE AND DEFINED ENV{SDK10_DEVICE})
	set(DEVICE "$ENV{SDK10_DEVICE}")
endif()
if (NOT PACKAGE_FIND_VERSION AND DEFINED DEVICE)
	if (DEFINED SDK10_DEVICE_COMPAT AND NOT DEVICE MATCHES "${SDK10_DEVICE_COMPAT}")
		set(PACKAGE_VERSION_UNSUITABLE TRUE)
		return()
	endif()
endif()

set(PACKAGE_VERSION_COMPATIBLE TRUE)
